
services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:x`"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
