def build_gpt_prompt(query, context_blocks, opa, opb, opc, opd, correct_answer, explanation):
    return (
        "You are a clinical MCQ improvement assistant with expertise in medical education.\n"
        "Your task is to analyze a new MCQ along with relevant validated examples and:\n"
        "1. Verify and correct any ambiguity or inaccuracy in the question.\n"
        "2. Enhance the options for clarity, precision, and clinical relevance.\n"
        "3. Confirm or revise the correct answer with evidence-based reasoning.\n"
        "4. Improve the explanation to be concise, structured, and medically sound.\n"
        "5. Return the entire output in strict JSON format.\n\n"
        "Use the following past MCQ examples for context:\n"
        
        f"{chr(10).join(context_blocks[:3])}\n\n"
        f"=== NEW MCQ ===\n"
        f"Question: {query}\n"
        f"Option A: {opa}\n"
        f"Option B: {opb}\n"
        f"Option C: {opc}\n"
        f"Option D: {opd}\n"
        f"Correct Answer: {correct_answer}\n"
        f"Explanation: {explanation}\n\n"
        "🧠 Guidelines:\n"
        "- Keep the improved question concise and clinically focused.\n"
        "- Ensure only one best answer; eliminate overlap or ambiguity.\n"
        "- Use current medical guidelines, pathophysiology, or diagnostic criteria.\n"
        "- Do NOT introduce new concepts not present in the question.\n"
        "- Keep the format strict; no markdown or extra commentary.\n\n"
        "- Make sure the improved MCQ is clinically accurate and clear.\n"
        "- Use precise medical terminology.\n"
        "- Ensure only one clearly correct answer.\n"
        "- Avoid vague language, invented data, or repeated question text.\n\n"
        "📋 Output Format Guidelines:\n"
        "- Use JSON only (no markdown, no explanations outside JSON).\n"
        "- improved_explanation should be structured into:\n"
        "  • 'overview': background of the concept\n"
        "  • 'correct_option': reason for correct answer\n"
        "  • 'others': dictionary with A, B, D (excluding correct one)\n"
        "- Add 'high_yield_synopsis': 2–5 bullet points clinically relevant to the topic\n\n"
        "⚠️ Strict Output Requirement: Respond ONLY with a single valid JSON object in the following format:\n"
        "📋 Required Explanation Format:\n"
        "Explanation:\n"
        "- Overview: Brief summary of the clinical scenario or key concept.\n"
        "- Correct Option: Why this option is correct using medical reasoning.\n"
        "- Incorrect Options: Why the other options are incorrect or less likely.\n\n"
        "✅ Return the result strictly in this JSON structure:\n"
        "✅ Return output in **exact** JSON structure:\n"
        "Use the following past MCQ examples for reference:\n"
        "Please return output as JSON:\n"
        "{\n"
        "  \"improved_question\": \"...\",\n"
        "  \"improved_options\": {\n"
        "    \"A\": \"...\",\n"
        "    \"B\": \"...\",\n"
        "    \"C\": \"...\",\n"
        "    \"D\": \"...\"\n"
        "  },\n"
        "  \"correct_answer\": \"A/B/C/D\",\n"
        "  \"improved_explanation\": {\n"
        "    \"overview\": \"...\",\n"
        "    \"correct_option\": \"...\",\n"
        "    \"others\": {\n"
        "      \"<A/B/C/D>\": \"...\",\n"
        "      \"<A/B/C/D>\": \"...\",\n"
        "      ...\n"
        "    }\n"
        "  },\n"
        "  \"high_yield_synopsis\": [\n"
        "    \"...\",\n"
        "    \"...\",\n"
        "    \"...\"\n"
        "  ]\n"
        "}"
    )

def build_gpt_prompt2(subject, context_blocks, pearl_title, pearl_desc,question):
    return (
        "I need help improving Multiple Choice Questions (MCQs) that I submit, along with refining the options for clarity and accuracy. "
        "I have submitted a MCQ with options, correct answer and complete explanation. "
        "Along with the MCQ, there is also relevant information on the MCQ from our internal database. Here's what I expect:\n\n"

        "🛠️ MCQ Improvement:\n"
        "- Review the entire question and rewrite it in a clearer, more precise format if necessary.\n"
        "- Check for duplicate options, spelling errors, and grammatical mistakes, and improve the wording of the options while ensuring they remain relevant to the clinical context.\n"
        "- Correct any inconsistencies or ambiguities in the question or options.\n"
        "- If any acronyms are used in the question or options, please expand them to remove ambiguity.\n\n"

        "✅ Correct Answer Identification:\n"
        "- Confirm the correct answer based on clinical evidence and rationale. If the initial answer is incorrect, explain why.\n"
        "- Provide a detailed explanation for the correct answer with step-by-step clinical reasoning.\n"
        "- For each option, explain why it is correct or incorrect and identify relevant clinical features or concepts.\n\n"

        "🩺 Clinical Diagnosis & Management:\n"
        "- Interpret clinical presentations, lab values (e.g., ABG, electrolytes), and imaging (X-rays, CT) to support your diagnosis and management.\n"
        "- Ensure the correct diagnosis and best next steps for management are clearly explained.\n\n"

        "🔪 Surgical & Pharmacologic Considerations:\n"
        "- Describe surgical procedures or complications if applicable.\n"
        "- Detail pharmacologic treatments, especially in contraindicated settings (e.g., renal insufficiency).\n\n"

        "🧠 Explanation & Diagnostic Reasoning:\n"
        "- Provide structured and clear reasoning for the correct answer.\n"
        "- Rule out incorrect answers with appropriate clinical justification.\n\n"

        "🖼️ Image-Based MCQs:\n"
        "- If an image is part of the MCQ, describe what is shown and how it supports the correct answer.\n"
        "- Ensure image-based diagnostic clues are clearly interpreted.\n\n"

        "📘 Output Format:\n"
        "- Final Improved Question (Retain image reference if present).\n"
        "- Improved Options (Remove duplicate/irrelevant ones).\n"
        "- Correct Answer.\n"
        "- Detailed Explanation, including:\n"
        "  • Explanation of the image (if present).\n"
        "  • Explanation of the Clinical Scenario.\n"
        "  • Explanation of the Correct Answer.\n"
        "  • Explanation of Incorrect Options.\n"
        "  • Additional key points from the topic.\n\n"
        "- High-Yield Review Synopsis (like Pearls and Treasures):\n"
        "  • Use bullet points.\n"
        "  • Include clinical facts likely to be tested.\n\n"

        "🔍 Use any explanation or write-up already provided along with your own knowledge base to extract relevant points for a refined explanation and topic synopsis.\n\n"

        "Here are 3 validated past MCQ examples for context:\n"
        f"{chr(10).join(context_blocks[:3])}\n\n"

        "=== NEW MCQ ===\n"
        f"Question: {question}\n"
        f"Subject: {subject}\n"
        f"Pearl title: {pearl_title}\n"
        f"Pearl Description: {pearl_desc}\n\n"
    )